apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kub-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-kub-server
  template:
    metadata: 
      labels:
        app: docker-kub-server
    spec: 
      containers:
        - name: server-node
          image: alisonv2/docker-kub
          imagePullPolicy: Always
          livenessProbe: 
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
